name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        uses: ./.github/actions/lint
      - name: Deploy
        uses: ./.github/actions/deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
